name: Deploy Complaint App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image
      run: docker build -t complaint-app .

    - name: Tag Docker Image
      run: docker tag complaint-app:latest ${{ secrets.ECR_URI }}:latest

    - name: Push Docker Image
      run: docker push ${{ secrets.ECR_URI }}:latest

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
